name: Build & Push Docker Image

on:
  workflow_dispatch:
  
  workflow_run:
    workflows: ["Sync fork"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Scarica il codice
        uses: actions/checkout@v4

      - name: Login al GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compila e Carica l'immagine
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.bk
          push: true
          tags: ghcr.io/alessiocav2004-byte/icvfork:latest
